version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: andre-seerr_server_1
      APP_PORT: 5055
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    restart: on-failure
    environment:
      - TZ=Europe/Oslo
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config